import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        cream: {
          DEFAULT: "#1a1e24",
          50: "#24272b",
          100: "#2b2f34",
          200: "#34383d",
          300: "#43474d",
        },
        beige: {
          DEFAULT: "#2b2f34",
          soft: "#3a2d2d",
        },
        olive: {
          DEFAULT: "#7c93b5",
          50: "#122b48",
          100: "#1a3555",
          200: "#27496d",
          300: "#b1c8ed",
          400: "#7c93b5",
          500: "#7c93b5",
          600: "#314866",
          700: "#d3e3ff",
        },
        coffee: {
          DEFAULT: "#0e8994",
          light: "#73d5e1",
          dark: "#001f23",
        },
        espresso: {
          DEFAULT: "#f2f0ed",
          light: "#c4c6ce",
        },
        muted: {
          DEFAULT: "#c4c6ce",
          light: "#a3a6ad",
        },
        danger: {
          DEFAULT: "#c35b3f",
          light: "#ffdad6",
        },
        warning: {
          DEFAULT: "#d99b26",
          light: "#ffdeae",
        },
        dark: {
          bg: "#1a1e24",
          surface: "#24272b",
          surfaceHover: "#30343a",
          border: "#4a4e55",
          text: "#f2f0ed",
          textSecondary: "#c4c6ce",
          muted: "#9a9da4",
        },
        lapis: "#122b48",
        dashboard: "#0a1020",
        "dashboard-surface": "#111a2e",
        "dashboard-raised": "#16233b",
        "dashboard-line": "#1d2b44",
        "dashboard-mountain": "#101a2c",
        "dashboard-mountain-back": "#0c1424",
        "dashboard-foreground": "#f2f5fb",
        "dashboard-muted": "#9aa8c4",
        erp: "#4f86ff",
        accounting: "#22e6b0",
        crm: "#9b5cf6",
        "signal-bright": "#22e6b0",
        "accent-blue": "#4f86ff",
        "accent-purple": "#9b5cf6",
        "accent-yellow": "#f5c542",
        "accent-red": "#ff5a6e",
        turquoise: "#0e8994",
        saffron: "#d99b26",
        pistachio: "#4e8752",
        terracotta: "#c35b3f",
        rosewater: "#4a2d2d",
        walnut: "#1a1e24",
        parchment: "#f2f0ed",
        canvas: "rgb(var(--farman-canvas) / <alpha-value>)",
        surface: "rgb(var(--farman-surface) / <alpha-value>)",
        raised: "rgb(var(--farman-raised) / <alpha-value>)",
        ink: "rgb(var(--farman-ink) / <alpha-value>)",
        "ink-soft": "rgb(var(--farman-ink-soft) / <alpha-value>)",
        "ink-faint": "rgb(var(--farman-ink-faint) / <alpha-value>)",
        line: "rgb(var(--farman-line) / <alpha-value>)",
        "line-strong": "rgb(var(--farman-line-strong) / <alpha-value>)",
        signal: "rgb(var(--farman-signal) / <alpha-value>)",
        "signal-soft": "rgb(var(--farman-signal-soft) / <alpha-value>)",
        "signal-ink": "rgb(var(--farman-signal-ink) / <alpha-value>)",
        waiting: "rgb(var(--farman-waiting) / <alpha-value>)",
        "waiting-soft": "rgb(var(--farman-waiting-soft) / <alpha-value>)",
        blocked: "rgb(var(--farman-blocked) / <alpha-value>)",
        "blocked-soft": "rgb(var(--farman-blocked-soft) / <alpha-value>)",
        done: "rgb(var(--farman-done) / <alpha-value>)",
        "done-soft": "rgb(var(--farman-done-soft) / <alpha-value>)",
        "farman-danger": "rgb(var(--farman-danger) / <alpha-value>)",
        "farman-danger-soft": "rgb(var(--farman-danger-soft) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-vazirmatn)", "var(--font-jakarta-latin)", "var(--font-jakarta-arabic)", "var(--font-peyda)", "system-ui", "sans-serif"],
        farman: ["var(--font-vazirmatn)", "var(--font-jakarta-latin)", "var(--font-jakarta-arabic)", "var(--font-peyda)", "system-ui", "sans-serif"],
        display: ["var(--font-vazirmatn)", "var(--font-playfair-latin)", "var(--font-playfair-arabic)", "var(--font-peyda)", "Georgia", "serif"],
        mono: ["var(--font-vazirmatn)", "var(--font-jakarta-latin)", "var(--font-jakarta-arabic)", "var(--font-peyda)", "monospace"],
      },
      borderRadius: {
        "2xs": "0.25rem",
        xs: "0.25rem",
        sm: "0.375rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
      },
      boxShadow: {
        soft: "0 4px 16px rgba(0, 0, 0, 0.24), 0 2px 6px rgba(217, 155, 38, 0.05)",
        card: "0 4px 16px rgba(0, 0, 0, 0.24), 0 2px 6px rgba(217, 155, 38, 0.05)",
        elevated: "0 12px 32px rgba(0, 0, 0, 0.42)",
        "dark-soft": "0 4px 16px rgba(0, 0, 0, 0.24)",
        "dark-card": "0 4px 16px rgba(0, 0, 0, 0.24)",
        "dark-elevated": "0 12px 32px rgba(0, 0, 0, 0.42)",
        blueprint: "0 4px 16px rgba(0, 0, 0, 0.24), 0 2px 6px rgba(217, 155, 38, 0.05)",
        raised: "0 12px 32px rgba(0, 0, 0, 0.42)",
        decision: "0 0 0 1px #d99b26, 0 4px 14px rgba(217, 155, 38, 0.22)",
        "focus-ring": "0 0 0 3px rgba(14, 137, 148, 0.15)",
      },
      spacing: {
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        gutter: "1.25rem",
        "gutter-mobile": "0.75rem",
        margin: "2rem",
        "margin-mobile": "1rem",
      },
      maxWidth: {
        workspace: "90rem",
        reading: "46rem",
      },
      transitionTimingFunction: {
        blueprint: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
      keyframes: {
        "activity-sweep": {
          "0%": { transform: "translateX(-110%)" },
          "100%": { transform: "translateX(260%)" },
        },
        "soft-enter": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "decision-pop": {
          "0%": { opacity: "0", transform: "scale(0.98)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "activity-sweep": "activity-sweep 2.2s cubic-bezier(0.4, 0, 0.2, 1) infinite",
        "soft-enter": "soft-enter 280ms cubic-bezier(0.2, 0.8, 0.2, 1)",
        "decision-pop": "decision-pop 220ms cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
