import { requireSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { Card, CardHeader, PageHeader, Badge, EmptyState, StatCard, SectionTitle } from "@/components/ui";
import { BusinessTaskList } from "@/components/business-task-list";
import Link from "next/link";
import { ClipboardList, PlusCircle } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function BusinessTasksPage() {
  const session = await requireSession();
  const businesses = await db.business.findMany({
    where: { companyId: session.companyId },
    orderBy: { createdAt: "desc" },
    include: { tasks: { orderBy: { phaseOrder: "asc" } } },
  });

  const totalTasks = businesses.reduce((a, b) => a + b.tasks.length, 0);
  const doneTasks = businesses.reduce((a, b) => a + b.tasks.filter((t) => t.done).length, 0);

  return (
    <div>
      <PageHeader
        title="Business Tasks"
        description="Execution plans generated by the Business Agent for each of your ventures."
        actions={
          <Link href="/business/setup" className="inline-flex items-center gap-2 h-9 rounded-lg bg-accent px-3.5 text-[13px] font-semibold text-[#04211d] hover:bg-accent-strong transition-colors">
            <PlusCircle className="h-4 w-4" /> New Business
          </Link>
        }
      />

      {businesses.length === 0 ? (
        <Card>
          <EmptyState
            icon={<ClipboardList className="h-5 w-5" />}
            title="No businesses yet"
            description="Describe a business idea in Business Setup and FARMAN will generate an executable workspace with phased tasks."
            action={
              <Link href="/business/setup" className="inline-flex items-center gap-2 h-9 rounded-lg bg-accent px-4 text-[13px] font-semibold text-[#04211d] hover:bg-accent-strong transition-colors">
                Start a business →
              </Link>
            }
          />
        </Card>
      ) : (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-3 gap-3 mb-5">
            <StatCard label="Ventures" value={String(businesses.length)} sub={businesses.map((b) => b.name).join(", ").slice(0, 60)} />
            <StatCard label="Open tasks" value={String(totalTasks - doneTasks)} tone={totalTasks - doneTasks > 0 ? "warn" : "good"} />
            <StatCard label="Completed" value={`${totalTasks ? Math.round((doneTasks / totalTasks) * 100) : 0}%`} tone="good" />
          </div>

          {businesses.map((b) => (
            <Card key={b.id} className="mb-5">
              <CardHeader
                title={b.name}
                subtitle={b.concept.slice(0, 120)}
                action={
                  <Link href={`/business/${b.id}`} className="text-xs text-accent hover:underline shrink-0">
                    Open workspace →
                  </Link>
                }
              />
              <BusinessTaskList tasks={b.tasks.map((t) => ({ id: t.id, title: t.title, detail: t.detail, phase: t.phase, done: t.done }))} />
            </Card>
          ))}
        </>
      )}
    </div>
  );
}
