import Link from "next/link";
import { type ReactNode } from "react";
import { StatItem, type StatItemProps } from "./StatItem";

type ModuleKind = "erp" | "accounting" | "crm";
type ModuleStat = StatItemProps;

const moduleStyle = {
  erp: { text: "text-accent-blue", border: "border-accent-blue/30", glow: "shadow-[0_0_34px_rgba(79,134,255,0.12)]", button: "border-accent-blue/35 bg-dashboard-surface text-dashboard-foreground hover:border-accent-blue/70" },
  accounting: { text: "text-signal-bright", border: "border-signal-bright/35", glow: "shadow-[0_0_48px_rgba(34,230,176,0.18)]", button: "border-transparent bg-gradient-to-l from-signal-bright to-pistachio text-dashboard hover:brightness-110" },
  crm: { text: "text-accent-purple", border: "border-accent-purple/30", glow: "shadow-[0_0_34px_rgba(155,92,246,0.12)]", button: "border-accent-purple/35 bg-dashboard-surface text-dashboard-foreground hover:border-accent-purple/70" },
};

function ModuleIcon({ kind }: { kind: ModuleKind }) {
  if (kind === "erp") return <svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z" /><path d="m4 7.5 8 4.5 8-4.5M12 12v9M8 5.2l8 4.6" /></svg>;
  if (kind === "accounting") return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><ellipse cx="12" cy="6" rx="6" ry="3" /><path d="M6 6v5c0 1.7 2.7 3 6 3s6-1.3 6-3V6M6 11v5c0 1.7 2.7 3 6 3s6-1.3 6-3v-5" /></svg>;
  return <svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="9" cy="8" r="3" /><circle cx="17" cy="10" r="2.5" /><path d="M3.5 19a5.5 5.5 0 0 1 11 0M14 19a4.5 4.5 0 0 1 6.5-3" /></svg>;
}

export function ModuleRing({ kind, label, subtitle, percent, stats, href, buttonLabel, featured = false }: { kind: ModuleKind; label: string; subtitle: string; percent: number; stats: ModuleStat[]; href: string; buttonLabel: string; featured?: boolean }) {
  const style = moduleStyle[kind];
  return <Link href={href} dir="rtl" aria-label={`${label}؛ عملکرد کلی ${percent} درصد`} className={`group relative mx-auto flex flex-col items-center text-center transition-transform duration-300 hover:-translate-y-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal-bright ${featured ? "max-w-[380px]" : "max-w-[300px]"}`}><div className={`relative flex items-center justify-center rounded-full border border-dashboard-line/80 bg-dashboard ${featured ? "-translate-y-[13px] shadow-[0_0_42px_rgba(34,230,176,0.28)] h-[clamp(260px,32vw,345px)] w-[clamp(260px,32vw,345px)]" : "translate-y-[31px] h-[clamp(220px,27vw,255px)] w-[clamp(220px,27vw,255px)]"}`}><svg viewBox="0 0 200 200" className="absolute inset-0 h-full w-full -rotate-90" aria-hidden="true"><circle cx="100" cy="100" r="85" pathLength="100" className="fill-none stroke-dashboard-raised" strokeWidth="30" /><circle cx="100" cy="100" r="85" pathLength="100" className={`fill-none ${kind === "accounting" ? "" : style.text}`} stroke={kind === "accounting" ? "var(--color-signal-bright)" : "currentColor"} strokeWidth="30" strokeLinecap="round" strokeDasharray={`${percent} ${100 - percent}`} /></svg><div className="relative z-10 flex flex-col items-center px-6 text-center"><span className={`mb-3 inline-flex items-center justify-center rounded-full border border-dashboard-line bg-dashboard-surface ${featured ? "h-16 w-16" : "h-14 w-14"} ${style.text}`}><ModuleIcon kind={kind} /></span><h3 className={`${featured ? "text-lg" : "text-base"} font-bold text-dashboard-foreground`}>{label}</h3><p className="mt-1 max-w-[170px] text-[10px] leading-4 text-dashboard-muted">{subtitle}</p><p className={`mt-3 font-mono font-semibold tracking-[-0.07em] text-dashboard-foreground ${featured ? "text-4xl" : "text-3xl"}`}>{percent}%</p><p className="mt-1 text-[10px] font-semibold text-dashboard-foreground">عملکرد کلی</p></div></div><div className={`${featured ? "mt-0" : "mt-[60px]"} grid w-full grid-cols-3 gap-2 pt-0 ${featured ? "mt-4" : ""}`}>{stats.map((stat) => <StatItem key={stat.label} {...stat} />)}</div><span className={`inline-flex min-h-10 w-fit items-center justify-center gap-2 rounded-full border px-5 text-[11px] font-semibold transition-all ${style.button} ${featured ? "mt-10 min-h-[52px] min-w-[240px]" : "mt-[46px] min-h-[44px] min-w-[196px]"}`}>{buttonLabel}<span aria-hidden="true" className="transition-transform group-hover:-translate-x-1">←</span></span></Link>;
}
